a=True
b=True 
c=True
d=True
print(c)
print(d)
print(not (a))
print(not b)
print(not c)
print(not d)
print(a and b)
print(a or b)
print(a and c)
print(a or c)
print(a and d)
print(a  or d)
print(b and c)
print(b or c)
print(a and b or c)
print(a or b and c)
print(a and b and c )
print(a or b or c)
print(not a and b and c)
print(not a or b or c)
print(not(a and b and c))
print(not(a or b or c))
print(not a and not b or not c)
print(not a or not b or not c)
print(not(not a or  not b or not c))